name: CI Workflow
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  lint-format:
    runs-on: ubuntu-latest
    name: Setup, Format and Enforce Eslint Rules
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci

      - name: Format Files and Enforce Eslint Rules
        run: npx lint-staged
